<?php 
include 'koneksi.php';
$sliders = $conn->query("SELECT * FROM sliders ORDER BY id DESC");
?>

<div class="slider-container relative w-[90%] h-[200px] md:h-[400px] sm:h-[300px] lg:h-[500px] overflow-hidden mx-auto bg-gray-200 rounded-xl">
    <div class="slides relative h-full">
            <?php 
                    $index = 0;
                            while($row = $sliders->fetch_assoc()): 
                                    ?>
                                            <a class="slide absolute inset-0 transition-opacity duration-700 ease-in-out <?= $index === 0 ? 'opacity-100 z-10' : 'opacity-0 z-0' ?>" 
                                                       href="uploads/<?= $row['image'] ?>" data-fancybox="sliders"
                                                                  data-caption="<?= htmlspecialchars($row['title']) ?>">
                                                                              <img src="uploads/<?= $row['image'] ?>" alt="<?= htmlspecialchars($row['title']) ?>" class="w-full h-full object-cover rounded-xl" />
                                                                                                  </a>
                                                                                                          <?php $index++; endwhile; ?>
                                                                                                              </div>

                                                                                                                  <!-- Tombol Navigasi -->
                                                                                                                      <button id="prevBtn" class="absolute left-3 top-1/2 -translate-y-1/2 bg-black/60 text-white p-3 rounded-full z-20">
                                                                                                                              &#10094;
                                                                                                                                  </button>
                                                                                                                                      <button id="nextBtn" class="absolute right-3 top-1/2 -translate-y-1/2 bg-black/60 text-white p-3 rounded-full z-20">
                                                                                                                                              &#10095;
                                                                                                                                                  </button>

                                                                                                                                                      <!-- Titik indikator -->
                                                                                                                                                          <div id="dots" class="absolute bottom-3 w-full flex justify-center gap-2 z-20">
                                                                                                                                                                  <?php for($i = 0; $i < $index; $i++): ?>
                                                                                                                                                                          <span class="dot w-3 h-3 rounded-full bg-gray-400 <?= $i === 0 ? 'bg-black' : '' ?>"></span>
                                                                                                                                                                                  <?php endfor; ?>
                                                                                                                                                                                      </div>
                                                                                                                                                                                      </div>

                                                                                                                                                                                      <!-- Script Slider -->
                                                                                                                                                                                      <script>
                                                                                                                                                                                      document.addEventListener("DOMContentLoaded", function () {
                                                                                                                                                                                          const slides = document.querySelectorAll(".slide");
                                                                                                                                                                                              const dots = document.querySelectorAll(".dot");
                                                                                                                                                                                                  const prevBtn = document.getElementById("prevBtn");
                                                                                                                                                                                                      const nextBtn = document.getElementById("nextBtn");

                                                                                                                                                                                                          let currentIndex = 0;

                                                                                                                                                                                                              function showSlide(index) {
                                                                                                                                                                                                                      slides.forEach((slide, i) => {
                                                                                                                                                                                                                                  slide.classList.remove("opacity-100", "z-10");
                                                                                                                                                                                                                                              slide.classList.add("opacity-0", "z-0");
                                                                                                                                                                                                                                                          dots[i].classList.remove("bg-black");
                                                                                                                                                                                                                                                                      dots[i].classList.add("bg-gray-400");
                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                      slides[index].classList.add("opacity-100", "z-10");
                                                                                                                                                                                                                                                                                              slides[index].classList.remove("opacity-0", "z-0");
                                                                                                                                                                                                                                                                                                      dots[index].classList.add("bg-black");
                                                                                                                                                                                                                                                                                                              dots[index].classList.remove("bg-gray-400");
                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                      function nextSlide() {
                                                                                                                                                                                                                                                                                                                              currentIndex = (currentIndex + 1) % slides.length;
                                                                                                                                                                                                                                                                                                                                      showSlide(currentIndex);
                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                              function prevSlide() {
                                                                                                                                                                                                                                                                                                                                                      currentIndex = (currentIndex - 1 + slides.length) % slides.length;
                                                                                                                                                                                                                                                                                                                                                              showSlide(currentIndex);
                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                      nextBtn.addEventListener("click", nextSlide);
                                                                                                                                                                                                                                                                                                                                                                          prevBtn.addEventListener("click", prevSlide);

                                                                                                                                                                                                                                                                                                                                                                              // Klik titik indikator
                                                                                                                                                                                                                                                                                                                                                                                  dots.forEach((dot, i) => {
                                                                                                                                                                                                                                                                                                                                                                                          dot.addEventListener("click", () => {
                                                                                                                                                                                                                                                                                                                                                                                                      currentIndex = i;
                                                                                                                                                                                                                                                                                                                                                                                                                  showSlide(currentIndex);
                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                  // Auto slide setiap 5 detik
                                                                                                                                                                                                                                                                                                                                                                                                                                      setInterval(nextSlide, 5000);
                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                      </script>